{
 "title": "Model monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "model",
    "query": {
     "query": "query_result(sum(istio_requests_total{namespace=\"models\"}) by (destination_service_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(sum(rate(inference_request_duration_seconds_sum{app=\"inference-api\", modelName=\"$model\"}[15s]))/sum(rate(inference_request_duration_seconds_count{app=\"inference-api\", modelName=\"$model\"}[15s])))*1000",
     "legendFormat": "request duration"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (statusCode) (count_over_time({app=\"$model\"}  |= \"statusCode\" | json [$__interval]))",
     "legendFormat": "HTTP Status: {{statusCode}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{app=\"$model\"}[10s]))/10",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (statusCode) (count_over_time({app=\"$model\"}  |= \"statusCode\" | json [$__interval]))",
     "legendFormat": "HTTP Status: {{statusCode}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$model.*\"}[30s]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"^$model.*\"} / (1024*1024))",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Instances count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=~\"^$model\"})",
     "legendFormat": "instances count"
    }
   ]
  }
 ]
}