{
 "title": "PVC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PVC Current Total Size (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim) / 1073750000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Used %age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Current Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim) / 1073750000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}