{
 "title": "Service monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "query_result(sum(istio_requests_total{namespace=\"dlframe\"}) by (destination_service_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$service.*\"}[30s]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"^$service.*\"} / (1024*1024))",
     "legendFormat": "memory usage (mb)"
    }
   ]
  },
  {
   "title": "AVG request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(sum(rate(istio_request_duration_milliseconds_sum{app=\"$service\"}[10s]))/sum(rate(istio_request_duration_milliseconds_count{app=\"$service\"}[10s])))",
     "legendFormat": "request duration (ms)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{app=\"$service\"}[10s]))/10",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "Instances count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=~\"^$service.*\"})",
     "legendFormat": "instances count"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"$service\", pod=~\"^$service.*\"}"
    }
   ]
  }
 ]
}